apiVersion: v2
name: voting-app
description: A Helm chart for the Voting Application
type: application
version: 1.0.0
appVersion: "2.0"
keywords:
  - voting
  - microservices
  - flask
  - nodejs
  - dotnet
maintainers:
  - name: DevOps Team

