apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voting-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - worker-deployment.yaml
  - vote-deployment.yaml
  - vote-service.yaml
  - result-deployment.yaml
  - result-service.yaml
  - ingress-nginx.yaml

