apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voting-app.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
data:
  OPTION_A: {{ .Values.vote.env.OPTION_A | quote }}
  OPTION_B: {{ .Values.vote.env.OPTION_B | quote }}
  PORT: {{ .Values.result.env.PORT | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  REDIS_HOST: redis
  POSTGRES_HOST: postgres

