{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    name: {{ .Values.namespace.name }}
    {{- if .Values.security.podSecurityStandards }}
    pod-security.kubernetes.io/enforce: {{ .Values.security.podSecurityStandards.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.security.podSecurityStandards.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.security.podSecurityStandards.warn }}
    {{- end }}
{{- end }}

