{{- if .Values.result.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-result
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app: result
    tier: frontend
spec:
  type: {{ .Values.result.service.type }}
  ports:
  - port: {{ .Values.result.service.port }}
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    {{- include "voting-app.selectorLabels" . | nindent 4 }}
    app: result
    tier: frontend
{{- end }}

