{{- if .Values.vote.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-vote
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app: vote
    tier: frontend
spec:
  type: {{ .Values.vote.service.type }}
  ports:
  - port: {{ .Values.vote.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "voting-app.selectorLabels" . | nindent 4 }}
    app: vote
    tier: frontend
{{- end }}

